### PR TITLE
Fix action not working on debians and in containers

### LINKED ISSUE #44: Unable to run the action inside docker
I have a job set up as follows (github public runner):
```yaml
    runs-on: ubuntu-20.04
```
And then a step (you may take a look at the workflow file [here](https://github.com/tarantool/vshard/blob/686bde3fc29410ce6ebc22f8a5e499eaa8e4c984/.github/workflows/fast_testing.yml#L42-L46) ):
```yaml
      - name: Install tarantool ${{ matrix.tarantool }}
        if: startsWith(matrix.tarantool, 'release') != true
        uses: tarantool/setup-tarantool@v2
        with:
          tarantool-version: ${{ matrix.tarantool }}
```
The workflow passes fine, but if I change `runs-on` to:
```yaml
    runs-on: ubuntu-20.04-self-hosted                                            
    container:                                                                   
      image: docker.io/tarantool/testing:ubuntu-focal
```
or
```yaml
    runs-on: ubuntu-20.04-self-hosted                                            
    container:                                                                   
      image: ubuntu:20.04
```
The job starts failing like this:
```
Caching APT packages: build-essential, cmake, cmake-data, dpkg-dev, fakeroot, g++, g++-9, libalgorithm-diff-perl, libalgorithm-diff-xs-perl, libalgorithm-merge-perl, libarchive13:amd64, libcurl4:amd64, libdpkg-perl, libfakeroot:amd64, libfile-fcntllock-perl, libicu66:amd64, libjsoncpp1:amd64, liblocale-gettext-perl, librhash0:amd64, libstdc++-9-dev:amd64, libunwind8:amd64, libuv1:amd64, libxml2:amd64, make, tarantool, tarantool-common, tarantool-dev
Error: ENOENT: no such file or directory, stat '/usr/share/doc/build-essential/AUTHORS'
```

The problem is described in https://github.com/tarantool/setup-tarantool/pull/41#discussion_r1273641890 and should be fixed by #41

### PR DESCRIPTION
**Pull request by grafin**
There are two problems preventing this action working on debian (not ubuntu) and in containers. This PR fixes them, as well as some issues in our CI, preventing the tests to pass. See commit messages for more info.

Closes #44

### CODE REVIEW

File: src/main.ts [hunk 1]
```diff
@@ -170,6 +175,91 @@ export async function latest_version(version_prefix: string): Promise<string> {
...
+
+  dpkgConfig.includes.forEach(include => {
+    if (include.test(filepath)) {
+      included = true
+      return
+    }
+  })
+
+  return included
+}
```
Comment (Totktonada) [inline src/main.ts:270]: AFAIU, we can't split `excludes` and `includes` into two arrays, because their order matters. From [man 1 dpkg](https://man7.org/linux/man-pages/man1/dpkg.1.html):

> --path-exclude=glob-pattern
> --path-include=glob-pattern
>
> \<...\>
>
> These two options can be specified multiple times, and
> interleaved with each other. Both are processed in the given
> order, with the last rule that matches a file name making the
> decision.

From [man 5 dpkg.cfg](https://man7.org/linux/man-pages/man5/dpkg.cfg.5.html):

> This file contains default options for dpkg. Each line contains a
> single option which is **exactly the same as a normal command line
> option** for dpkg except for the leading hyphens which are not used
> here.

In other words, includes have no precedence over excludes.

(TBH, I guess that your solution should anyway work for all the practical cases, but since we already have a general solution with parsing of the configuration and it is not a big deal to match the `dpkg` behavior exactly, it would be nice to implement it this way.)

----

While we're here, two typos from the commit message:

> This file is installed because it matches exclude-path in dpgk config,

* installed -> not installed
* dpgk -> dpkg

File: .github/workflows/test-docker.yml [hunk 2]
```diff
@@ -0,0 +1,96 @@
...
+        # Only 2.11 is available on debian bookworm
+        include:
+          - tarantool: '2.11'
+            image: debian:bookworm
+
+    container:
+      image: ${{ matrix.image }}
+
+    env:
+      TARANTOOL_CACHE_KEY_SUFFIX: -DA-${{ github.run_id }}
```
Comment (Totktonada) [inline .github/workflows/test-docker.yml:33]: Shouldn't we include `${{ matrix.image }}` into the cache key? It seems that `${{ github.run_id }}` is shared across jobs generated from the same job matrix.

https://github.com/tarantool/setup-tarantool/blob/615e8f4e4dfbf4e41631a72660d27f1ede102aa0/.github/workflows/test.yml#L334-L337

File: .github/workflows/test-docker.yml [hunk 3]
```diff
@@ -0,0 +1,96 @@
...
+
+      - id: get-latest
+        run: |
+          node <<'SCRIPT'
+            process.env["INPUT_TARANTOOL-VERSION"] = "${{ matrix.tarantool }}"
+            require("./dist/main").latest_version("${{ matrix.tarantool }}").then(v => {
+              console.log(v)
+              require("./dist/main").setActionOutput('version', v);
+            })
+          SCRIPT
```
Comment (Totktonada) [inline .github/workflows/test-docker.yml:60]: Nit: It can be replaced with the `latest-version` action to reduce code duplication and to make the workflow code concise.

https://github.com/tarantool/setup-tarantool/blob/615e8f4e4dfbf4e41631a72660d27f1ede102aa0/.github/workflows/test.yml#L123-L126

File: .github/workflows/test-docker.yml [hunk 4]
```diff
@@ -0,0 +1,96 @@
...
+
+      - name: Setup from scratch
+        uses: ./
+        with:
+          tarantool-version: ${{ matrix.tarantool }}
+
+      - name: Check precise version
+        run: |
+          dpkg -s tarantool | grep '^Version: ${{ steps.get-latest.outputs.version }}'
+          # It'll also fail if tarantool is installed from cache but not from apt-get
```
Comment (Totktonada) [inline .github/workflows/test-docker.yml:70]: Nit: It can be replaced with the `verify-version` action to reduce code duplication.

https://github.com/tarantool/setup-tarantool/blob/615e8f4e4dfbf4e41631a72660d27f1ede102aa0/.github/workflows/test.yml#L134-L137

File: .github/workflows/test-docker.yml [hunk 5]
```diff
@@ -0,0 +1,96 @@
...
+
+      - name: Check branch version
+        run: |
+          T=$(tarantool -e 'print(_TARANTOOL:match("%d+%.%d+")); os.exit()')
+          if [ "$T" != "${{ matrix.tarantool }}" ]; then
+            echo "Tarantool version is $T, expected ${{ matrix.tarantool }}"
+            exit 1
+          else
+            echo "Tarantool version is $T, as expected"
+          fi
```
Comment (Totktonada) [inline .github/workflows/test-docker.yml:96]: Nit: It can be replaced with the `verify-version` action to reduce code duplication.

https://github.com/tarantool/setup-tarantool/blob/615e8f4e4dfbf4e41631a72660d27f1ede102aa0/.github/workflows/test.yml#L148-L151

File: .github/workflows/test.yml [hunk 6]
```diff
@@ -42,7 +42,7 @@ jobs:
           node <<'SCRIPT'
             process.env["INPUT_TARANTOOL-VERSION"] = "${{ matrix.tarantool }}"
             process.env["INPUT_NIGHTLY-BUILD"] = "${{ matrix.nightly }}"
-            require("./dist/main").latest_version().then(v => {
+            require("./dist/main").latest_version("${{ matrix.tarantool }}").then(v => {
```
Comment (Totktonada) [inline .github/workflows/test.yml:44]: Is `.github/actions/latest-version/action.yml` affected as well?

Comment (Totktonada) [reply .github/workflows/test.yml:44]: Got it. `2.10` is not a latest minor release of the series-2. `2.11` is the latest one. So, we need to add the `version_prefix` argument to the `latest_version` call here.

Regarding the `latest_version` action: its argument is called `tarantool-series` and it seems OK to pass it to `inputs.tarantool-version` and don't pass it to the `version_prefix` argument. If we need a version filtering from the action, its argument should be renamed or another argument is added. I'm OK to leave it without changes.

File: .github/workflows/test-docker.yml (hunk 3 above)
Comment (Totktonada) [reply .github/workflows/test-docker.yml:60]: Now I understood that we need to [adjust](https://github.com/tarantool/setup-tarantool/pull/45#discussion_r1501697662) the action for determining the latest 2.10 release (not just latest series-2 release). I'm OK if you just leave it as is (as well as all the other comments that are marked as nits). Just let me know about your decision.

**Comment by Totktonada** [comment]
Thank you for the decent work!

I would like to comment a situation with 'disappearing' of the tarantool-1.10.12 package (described by [this commit](https://github.com/tarantool/setup-tarantool/commit/358bbfec7465c5a2b46711be477706deaa55517b) from the PR). CI jobs that experience the problem use `runs-on: ubuntu-latest`. At the time of writing it meant Ubuntu Focal (20.04), but now it is Ubuntu Jammy (22.04). Tarantool `1.10` release series supports Ubuntu Jammy since the `1.10.14` release. There is no `1.10.12` package for Ubuntu Jammy.

I think we can build such package and deploy it to `download.tarantool.org` for convenience, but nothing actually stops us from using `1.10.14` in CI. I agree with your fix.

**Review by Totktonada — APPROVED** [review]
The patchset looks nice. I've nothing to add here except a few nits (see above).

Let's resolve them (or let me know that you're out of free time) and I'll proceed with the pull request.

File: .github/workflows/test-docker.yml [hunk 7]
```diff
@@ -0,0 +1,96 @@
+name: Test in docker
```
Comment (Totktonada) [inline .github/workflows/test-docker.yml:1]: BTW, this commit ('bugfix: missing files from installed deb packages') fixes #44. I would add `Fixes #44` into the commit and into the pull request description.

File: .github/workflows/test.yml (hunk 6 above)
Comment (grafin) [reply .github/workflows/test.yml:44]: I'm not sure `tarantool-version` works as intended right now. We set the `INPUT_TARANTOOL-VERSION` here, but it doesn't seem to be used in the code we call:

Comment (Totktonada) [reply .github/workflows/test.yml:44]: It is used in the `construct_base_url()`, which is called from here. In fact, it affects only release series (i. e. which repostiory is used), but doesn't perform version filtering within the repository. So, it doesn't distinguish 2.10 and 2.11, because they're in the same `series-2` repository.

Comment (grafin) [reply .github/workflows/test.yml:44]: How about the following patch? It will eliminate the necessity to provide argument
```diff
--- a/src/main.ts
+++ b/src/main.ts
@@ -165,7 +165,9 @@ async function available_versions(
     })
 }

-export async function latest_version(version_prefix: string): Promise<string> {
+export async function latest_version(
+  version_prefix: string = tarantool_version
+): Promise<string> {
   return available_versions(version_prefix).then(versions => {
     let max = ''
     versions.forEach(v => {
```

File: .github/workflows/test-docker.yml (hunk 3 above)
Comment (grafin) [reply .github/workflows/test-docker.yml]: for some reason the packages versioning is different for 1.10 and 2.10 (2.11) releases:
1.10
package: 1.10.15.0.ge14d0b4ea-1
abc: 1.10.15
abcd: 1.10.15.0
abc-d: 1.10.15-0
git-describe: 1.10.15-0-ge14d0b4ea

2.10 and 2.11
package: 2.10.8.g4472d9247f-1
abc: 2.10.8
abcd: 2.10.8.g4472d9247f
abc-d: 2.10.8-g4472d9247f
git-describe: 2.10.8-g4472d9247f-1

File: .github/workflows/test-docker.yml (hunk 2 above)
Comment (grafin) [reply .github/workflows/test-docker.yml]: Thanks! Fixed.

File: .github/workflows/test-docker.yml (hunk 5 above)
Comment (grafin) [reply .github/workflows/test-docker.yml]: Fixed.

File: .github/workflows/test-docker.yml (hunk 7 above)
Comment (grafin) [reply .github/workflows/test-docker.yml:1]: Fixed.

File: .github/workflows/test-docker.yml (hunk 3 above)
Comment (Totktonada) [reply .github/workflows/test-docker.yml]: The reason is the [new release policy](https://github.com/orgs/tarantool/discussions/6182#user-content-deb-package-versions-debian-ubuntu) that is in effect since 2.10.0. Now I remember that I left 2.10+ support in the `latest-version` action unimplemented, because it was not needed for my test cases.

https://github.com/tarantool/setup-tarantool/blob/615e8f4e4dfbf4e41631a72660d27f1ede102aa0/.github/actions/latest-version/action.yml#L28-L32

File: .github/workflows/test.yml (hunk 6 above)
Comment (Totktonada) [reply .github/workflows/test.yml]: I have no objections.

Alternatively we can just strip the argument. It seems, it interferes with the global `tarantool_version` in a confusing way.

<details>
<summary>Patch (untested)</summary>

```diff
diff --git a/src/main.ts b/src/main.ts
index 859c656..70b6a46 100644
--- a/src/main.ts
+++ b/src/main.ts
@@ -115,14 +115,12 @@ function construct_base_url(): string {
   )
 }
 
-async function available_versions(
-  version_prefix: string
-): Promise<Array<string>> {
+async function available_versions(): Promise<Array<string>> {
   const baseUrl = construct_base_url()
   const repo = baseUrl + '/ubuntu/dists/' + (await lsb_release())
 
   // Don't return 1.10.10, when the version prefix is 1.10.1.
-  const prefix = version_prefix ? version_prefix + '.' : ''
+  const prefix = tarantool_version + '.'
 
   return http_get(`${repo}/main/binary-amd64/Packages`)
     .then(response => {
@@ -140,7 +138,7 @@ async function available_versions(
           const match = paragraph.match(/^Version: (.+)$/m)
           if (match) {
             let v = match[1]
-            if (!prefix || v.startsWith(prefix)) {
+            if (v.startsWith(prefix)) {
               versions.push(v)
             }
           }
@@ -149,8 +147,8 @@ async function available_versions(
     })
 }
 
-export async function latest_version(version_prefix: string): Promise<string> {
-  return available_versions(version_prefix).then(versions => {
+export async function latest_version(): Promise<string> {
+  return available_versions().then(versions => {
     let max = ''
     versions.forEach(v => {
       max = semver_max(max, v)
@@ -166,7 +164,7 @@ async function run_linux(): Promise<void> {
     const baseUrl = construct_base_url()
 
     core.startGroup(`Checking latest tarantool ${tarantool_version} version`)
-    const version = await latest_version(tarantool_version)
+    const version = await latest_version()
     core.info(`${version}`)
     core.endGroup()
     if (core.getInput('cache-key')) {
```
</details>

File: .github/workflows/test-docker.yml (hunk 3 above)
Comment (grafin) [reply .github/workflows/test-docker.yml]: I've fixed it in the action itself:
https://github.com/tarantool/setup-tarantool/pull/45/commits/78abdce492f16a4ef0c6411840bc6c39124a8c9b

File: .github/workflows/test.yml (hunk 6 above)
Comment (grafin) [reply .github/workflows/test.yml]: I don't see a reason to strip it:
1) We may in future need to pass it explicitly
2) The diff is smaller with default value of the argument)

Let's leave it as is.

File: src/main.ts (hunk 1 above)
Comment (grafin) [reply src/main.ts:272]: It's not that easy:
consider the following case
```
--path-include=/usr/local/folder/file
--path-exclude=/usr/local/folder/*
```
In that order, should the `/usr/local/folder/file` be included or not? According to the man you provided - it should not, because only order is relevant (the more exact match doesn't win). There is also a problem if several config files with includes/excludes are present - the result is depended on the order in which the config files are processed. Shortly speaking - IMO their approach is bullshit) But I will try to replicate it as following:
1) Process config files in alphabetical order of the path
2) Create on array with structs like {type: 'exclude'/'include', path: 'regex'} in the order those options are read
3) For each file iterate over the array constructed in 2 with the final being the last found regex match and its type

Comment (grafin) [reply src/main.ts]: I've rewrote it according to the propose above see https://github.com/tarantool/setup-tarantool/compare/16f0e17a2a7fbaba50d742aaaafd5b00e4261f46..5a4e6640d41435e53d12468e113c834e0bead844

**Comment by grafin** [comment]
Thanks for in-depth review and help with figuring out some details! I've fixed everything you mentioned in your review, feel free merge if you have no further comments. I would also suggest rewriting `.github/workflows/test.yml` to use `latest-version` and `verify-version` now that they are fixed, but this is out of the scope of current PR.

File: .github/workflows/test-docker.yml (hunk 3 above)
Comment (Totktonada) [reply .github/workflows/test-docker.yml]: Nice, thank you!

File: .github/workflows/test.yml (hunk 6 above)
Comment (Totktonada) [reply .github/workflows/test.yml]: OK, no problems.

File: src/main.ts (hunk 1 above)
Comment (Totktonada) [reply src/main.ts]: I've no insight about precise algorithm: I know just what the man page says. Now it seems that our algorithm follows it.

Thank you for the update.

**Review by Totktonada — APPROVED** [review]
Looks good for me. Thanks!
